version: "3"

services:
  zookeeper:
    image: confluent/zookeeper
    ports:
      - "2181:2181"
    networks:
      - back-end

  kafka:
    image: confluent/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
    networks:
      - back-end

networks:
  back-end: